# Generated by Django 3.2.5 on 2021-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='age',
        ),
        migrations.AddField(
            model_name='kid',
            name='birth_date',
            field=models.CharField(default='birth date', max_length=350, verbose_name='Birth date'),
            preserve_default=False,
        ),
    ]
