# Generated by Django 3.2.5 on 2021-11-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0002_auto_20211118_0831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='health_status',
        ),
        migrations.AddField(
            model_name='kid',
            name='health_condition_notes',
            field=models.TextField(default='', verbose_name='Health condition notes'),
            preserve_default=False,
        ),
    ]
