# Generated by Django 3.2.5 on 2021-11-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0003_auto_20211118_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='gender',
            field=models.CharField(default='gender', max_length=350, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
