# Generated by Django 3.2.5 on 2021-11-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0004_kid_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='name',
            field=models.CharField(default='name', max_length=350, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
