# Generated by Django 3.2.5 on 2021-11-18 07:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('kids', '0006_auto_20211118_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='kid',
            name='hobbies',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
