# Generated by Django 3.2.5 on 2021-11-18 08:35

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('kids', '0007_auto_20211118_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='profile_pic',
            field=models.ImageField(default='profile.png', upload_to='kids_profile_pics', verbose_name='Profile pic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kid',
            name='hobbies',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Hobbies'),
        ),
    ]
