# Generated by Django 3.2.5 on 2021-12-14 18:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_auto_20211118_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
