# Generated by Django 3.2.5 on 2021-12-19 08:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0009_alter_kid_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
    ]
