# Generated by Django 3.2.5 on 2021-12-19 08:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0011_alter_kid_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='attachment',
            field=cloudinary.models.CloudinaryField(default='attachment.pdf', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
