# Generated by Django 3.2.7 on 2021-10-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='address', max_length=350, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='gov_id',
            field=models.CharField(default='gov id', max_length=350, verbose_name='GOV ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_num',
            field=models.CharField(default='phone num', max_length=350, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
