# Generated by Django 3.2.5 on 2021-11-24 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_remove_staffmember_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350, verbose_name='Title')),
                ('cover', models.ImageField(upload_to='announcements_cover_imgs')),
                ('body', models.TextField(verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is featured')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember', verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
