# Generated by Django 3.2.5 on 2021-11-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_remove_staffmember_cv'),
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=350, verbose_name='Class name')),
                ('class_cover', models.ImageField(upload_to='activity_classes_cover_images')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('class_member', models.ManyToManyField(to='kids.Kid', verbose_name='Class member')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember', verbose_name='Teacher')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='ClassActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=350, verbose_name='Activity')),
                ('starts_at', models.TimeField(verbose_name='Starts at')),
                ('activity_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_classes.activityclass')),
            ],
            options={
                'verbose_name': 'Class activity',
                'verbose_name_plural': 'Class activities',
            },
        ),
    ]
