# Generated by Django 3.2.5 on 2021-11-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staffmember_cv'),
        ('activity_classes', '0002_classpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember'),
        ),
    ]
