# Generated by Django 3.2.5 on 2021-11-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity_classes', '0003_classpost_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('class_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_classes.classpost', verbose_name='Class post')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Class post comment',
                'verbose_name_plural': 'Class post comments',
            },
        ),
    ]
