# Generated by Django 3.2.5 on 2021-11-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_classes', '0005_rename_class_member_activityclass_class_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactivity',
            name='activity_img',
            field=models.ImageField(default='activity_img.png', upload_to='class_activities_imgs', verbose_name='Activity image'),
            preserve_default=False,
        ),
    ]
