# Generated by Django 3.2.5 on 2021-11-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0008_auto_20211118_1035'),
        ('activity_classes', '0006_classactivity_activity_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassActivityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Rating')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_classes.classactivity')),
                ('activity_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity_classes.activityclass', verbose_name='Activity class')),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kid', verbose_name='Kid')),
            ],
            options={
                'verbose_name': 'Class activity rating',
                'verbose_name_plural': 'Class activity ratings',
            },
        ),
    ]
