# Generated by Django 3.2.5 on 2021-12-14 18:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_classes', '0007_classactivityrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityclass',
            name='class_cover',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='classactivity',
            name='activity_img',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
