# Generated by Django 3.2.5 on 2021-12-14 19:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity_classes', '0008_auto_20211214_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpost',
            name='post_attachment',
            field=cloudinary.models.CloudinaryField(default='file.mp4', max_length=255, verbose_name='file'),
            preserve_default=False,
        ),
    ]
