# Generated by Django 3.2.5 on 2021-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='initialized_between',
            field=models.CharField(default='initialized_between', max_length=250, verbose_name='Initialized between'),
            preserve_default=False,
        ),
    ]
