# Generated by Django 3.2.7 on 2021-10-07 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parent',
            options={'verbose_name': 'Parent', 'verbose_name_plural': 'Parents'},
        ),
        migrations.AddField(
            model_name='parent',
            name='job',
            field=models.CharField(default='job', max_length=350, verbose_name='Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='parent_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Parent account'),
        ),
        migrations.AddField(
            model_name='parent',
            name='qualification',
            field=models.CharField(default='qualification', max_length=350, verbose_name='Qualification'),
            preserve_default=False,
        ),
    ]
