# Generated by Django 3.2.5 on 2021-11-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start date'),
        ),
    ]
